name: Build distribution packages

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build_distributables:
        name: Build distributables
        runs-on: ubuntu-latest
        steps:
            - name: Install libraries
              run: "sudo apt-get update && sudo apt-get install -y make cmake dpkg rpm"

            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3

            - name: Checkout dependencies
              run: python -m pip install wheel setuptools numpy

            - name: Build all packages
              run: "(cd utils; make dist -j 5)"

            - name: Upload wheel
              uses: actions/upload-artifact@v3
              with:
                  name: wheel
                  path: ./dist/sihm*.whl

            - name: Upload deb
              uses: actions/upload-artifact@v3
              with:
                  name: deb
                  path: ./dist/sihm*.deb

            - name: Upload rpm
              uses: actions/upload-artifact@v3
              with:
                  name: rpm
                  path: ./dist/sihm*.rpm

            - name: Upload brew
              uses: actions/upload-artifact@v3
              with:
                  name: brew
                  path: ./dist/sihm*.rb
