name: Publish binary wheel and distribution packages

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build_and_test_distribution_packages:
        uses: ./.github/workflows/ci.yml
    publish_files:
        name: Publish files
        needs: [build_and_test_distribution_packages]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: wheel
                  path: ./dist
            - uses: actions/download-artifact@v4
              with:
                  name: rpm
                  path: ./dist
            - uses: actions/download-artifact@v4
              with:
                  name: deb
                  path: ./dist
            - uses: actions/download-artifact@v4
              with:
                  name: brew
                  path: ./dist
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./dist/sihm*
