name: Publish new release

on:
    release:
        types: [published]

    workflow_dispatch:
jobs:
    build_and_test_distribution_packages:
        uses: ./.github/workflows/test_all_dist.yml
    publish_dist_pkgs:
        name: Publish distribution packages
        needs: [build_and_test_distribution_packages]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: wheel
                  path: ./dist
            - uses: actions/download-artifact@v3
              with:
                  name: rpm
                  path: ./dist
            - uses: actions/download-artifact@v3
              with:
                  name: deb
                  path: ./dist
            - uses: actions/download-artifact@v3
              with:
                  name: brew
                  path: ./dist
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./dist/sihm*
    publish_PyPI:
        name: Upload wheels to PyPI
        runs-on: ubuntu-latest
        needs: [build_and_test_distribution_packages]
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: wheel
                  path: ./dist

            - name: Publish package to PyPI test
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
