name: Publish binary wheel and distribution packages

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build_and_test_distribution_packages:
        uses: ./.github/workflows/test_all_dist.yml
    publish_files:
        name: Publish files
        needs: [build_and_test_distribution_packages]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./sihm*
