name: Publish Wheels on PyPi

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build_and_test_distribution_packages:
        uses: ./.github/workflows/test_all_dist.yml
    upload_wheels:
        name: Upload wheels to PyPI
        runs-on: ubuntu-latest
        needs: [build_and_test_distribution_packages]
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: wheel
                  path: ./dist

            - name: Publish package to PyPI test
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
