name: Publish binary wheel and distribution packages

on:
    release:
        types: [published]

    workflow_dispatch:

jobs:
    build_distribution_packages:
        uses: ./.github/workflows/build_all_dist.yml
    publish_files:
        name: Publish files
        needs: [build_distribution_packages]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./sihm*
