name: Publish Wheels on Test PyPi

on:
    workflow_dispatch:

jobs:
    build_distribution_packages:
        uses: ./.github/workflows/build_all_dist.yml
    upload_wheels:
        name: Upload wheels to PyPI
        runs-on: ubuntu-latest
        needs: [build_distribution_packages]
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: wheel
                  path: ./dist

            - name: Publish package to PyPI test
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_TEST_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/
